import React, { useState, useEffect } from 'react'
import RAGPanel from '../../shared/RAGPanel'
import { consumeRestoreSession } from '../../../engine/archive'
import { askRAG } from '../../../engine/rag'

const cflKnowledge = [
  { language: 'a^n b^n c^n', isCFL: false, explanation: 'NOT context-free. Using the CFL pumping lemma: for s = aᵖbᵖcᵖ, any decomposition s=uvxyz with |vxy|≤p means v and y can span at most two of the three symbol groups. Pumping creates unequal counts.', p: 3, s: 'aaabbbccc', u: 'a', v: 'a', x: 'ab', y: 'b', z: 'bccc', pumped: ['aabbccc', 'aaabbbccc', 'aaaabbbbccc', 'aaaaabbbbbccc', 'aaaaaabbbbbbccc'] },
  { language: 'ww (exact copy)', isCFL: false, explanation: 'NOT context-free. The language {ww | w ∈ {a,b}*} requires matching positions across the string, which a PDA cannot do.', p: 3, s: 'abcabc', u: '', v: 'a', x: 'bc', y: 'a', z: 'bc', pumped: ['bcabc', 'abcabc', 'aabcaabc', 'aaabcaaabc', 'aaaabcaaaabc'] },
  { language: 'a^n b^n', isCFL: true, explanation: 'IS context-free! Generated by S → aSb | ε. A PDA can push a\'s and pop on b\'s.', p: 3, s: 'aaabbb', u: 'a', v: 'a', x: '', y: 'b', z: 'bb', pumped: ['aabb', 'aaabbb', 'aaaabbbb', 'aaaaabbbbb', 'aaaaaabbbbbb'] },
  { language: 'a^i b^j c^k where i=j or j=k', isCFL: true, explanation: 'IS context-free! Union of two CFLs: {aⁿbⁿcᵏ} ∪ {aⁱbⁿcⁿ}. CFLs are closed under union.', p: 2, s: 'aabbcc', u: 'a', v: 'a', x: 'bb', y: 'c', z: 'c', pumped: ['abbcc', 'aabbcc', 'aaabbbcc', 'aaaabbbbcc', 'aaaaabbbbbcc'] },
]

export default function CFLPumpingLemma() {
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<typeof cflKnowledge[0] | null>(null)
  const [pumpCount, setPumpCount] = useState(2)

  // Auto-load on mount
  useEffect(() => {
    setSelected(cflKnowledge[0])
    setQuery(cflKnowledge[0].language)
  }, [])

  useEffect(() => {
    const payload = consumeRestoreSession('cfl-pumping')
    if (payload) {
      setSelected(payload)
      setQuery(payload.language || "")
    }
  }, [])

  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [error, setError] = useState('')

  const search = async () => {
    const q = query.toLowerCase().replace(/\s+/g, '')
    if (!q) return
    setError('')
    const found = cflKnowledge.find(k => {
      const kq = k.language.toLowerCase().replace(/\s+/g, '')
      return kq === q || kq.includes(q) || q.includes(kq)
    })
    if (found) {
      setSelected(found)
      return
    }
    // Always use RAG for unknown languages
    setIsAnalyzing(true)
    try {
      const res = await askRAG('unit3',
        'Apply the CFL Pumping Lemma to L = { ' + query + ' }. ' +
        'Set p to 3 or 4. Pick a valid string s. Split as s=uvxyz with |vxy|<=p, |vy|>=1. ' +
        'Produce 5 pumped strings (i=0..4) as ACTUAL CHARACTER STRINGS, not algebra. ' +
        'Return JSON with: language, isCFL (bool), p (number), s, u, v, x, y, z (all strings), pumped (string[5]), explanation.'
      )
      if (res.payload && typeof res.payload === 'object') {
        setSelected(Object.assign({ pumped: [] }, res.payload as typeof cflKnowledge[0]))
      } else {
        setError('RAG did not return a structured result. Try rephrasing.')
      }
    } catch (e: any) {
      setError(e.message || 'Analysis failed.')
    } finally {
      setIsAnalyzing(false)
    }
  }

  const pumpedAtI = (i: number) => {
    if (!selected) return ''
    if (selected.pumped && selected.pumped[i] !== undefined) return selected.pumped[i]
    return (selected.u || '') + (selected.v || '').repeat(i) + (selected.x || '') + (selected.y || '').repeat(i) + (selected.z || '')
  }

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-8 fade-up">
        <span className="font-label text-primary tracking-[0.4em] uppercase text-xs mb-2 block">Unit 03 — CFL Properties</span>
        <h1 className="font-headline text-5xl md:text-7xl italic leading-[1.05] tracking-tighter text-fade-reveal">
          <span className="prism-text prism-underline active">CFL Pumping Lemma</span>
        </h1>
        <p className="mt-4 max-w-xl text-on-surface-variant font-body text-sm leading-relaxed">
          Prove whether a language is context-free using the pumping lemma for CFLs. The decomposition requires s = uvxyz.
        </p>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-4 space-y-4">
          <div className="glass-panel p-6 rounded-2xl fade-up" style={{ animationDelay: '0.1s' }}>
            <label className="font-label text-[10px] uppercase tracking-[0.3em] text-gold block mb-4">Ask About a Language</label>
            <input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && search()} className="w-full bg-transparent border-b-2 border-white/10 py-3 text-xl font-headline italic text-cream focus:outline-none focus:border-gold transition-colors" placeholder="e.g. a^n b^n c^n" />
            {error && <p className="text-red-400 text-xs mt-2">{error}</p>}
            <button onClick={search} disabled={isAnalyzing} className="mt-4 w-full py-3 prism-gradient rounded-lg text-[#131313] font-label text-[10px] uppercase tracking-wider font-bold cursor-pointer hover:scale-105 transition-transform disabled:opacity-50 flex justify-center items-center gap-2">
              {isAnalyzing ? (
                <><span className="w-3 h-3 rounded-full border-2 border-transparent border-t-[#131313] animate-spin" /> AI Analyzing...</>
              ) : 'Analyze'}
            </button>
          </div>
          <div className="glass-panel p-6 rounded-2xl fade-up" style={{ animationDelay: '0.15s' }}>
            <label className="font-label text-[10px] uppercase tracking-[0.3em] text-lavender/60 block mb-3">Known Languages</label>
            {cflKnowledge.map((k, i) => (
              <button key={i} onClick={() => { setSelected(k); setQuery(k.language); setError('') }} className={`w-full text-left px-3 py-2 rounded-lg transition-all cursor-pointer text-sm mb-1 border ${selected === k ? 'bg-gold/10 border-gold/30 text-gold scale-[1.02]' : 'hover:bg-white/5 text-on-surface-variant border-transparent'}`}>
                <span className="font-headline italic">{k.language}</span>
                <span className={`ml-2 text-[10px] font-label uppercase ${k.isCFL ? 'text-green-400' : 'text-red-400'}`}>{k.isCFL ? 'CFL' : 'Not CFL'}</span>
              </button>
            ))}
          </div>
        </div>
        <div className="lg:col-span-8">
          {selected ? (
            <div className="space-y-6">
              <div className="glass-panel p-8 rounded-2xl fade-up" style={{ animationDelay: '0.2s' }}>
                <div className="flex items-center gap-4 mb-6">
                  <span className={`text-3xl ${selected.isCFL ? 'drop-shadow-[0_0_15px_rgba(74,222,128,0.5)]' : 'drop-shadow-[0_0_15px_rgba(248,113,113,0.5)]'}`}>{selected.isCFL ? '🟢' : '🔴'}</span>
                  <div>
                    <h2 className="font-headline text-3xl italic text-cream">L = {`{${selected.language}}`}</h2>
                    <span className={`font-label text-xs uppercase tracking-wider ${selected.isCFL ? 'text-green-400' : 'text-red-400'}`}>{selected.isCFL ? 'Context-Free Language' : 'Not Context-Free'}</span>
                  </div>
                </div>
                <p className="text-on-surface-variant text-sm leading-relaxed bg-white/[0.02] p-4 rounded-xl border border-white/5">{selected.explanation}</p>
              </div>
              
              <div className="glass-panel p-6 rounded-2xl fade-up" style={{ animationDelay: '0.3s' }}>
                <label className="font-label text-[10px] uppercase tracking-[0.3em] text-lavender/60 block mb-4">Decomposition s = uvxyz (p = {selected.p})</label>
                <div className="flex flex-wrap items-center gap-2 mb-6">
                  <span className="text-on-surface-variant text-sm mr-2 font-headline italic text-xl">s = </span>
                  <div className="flex shadow-lg rounded-lg overflow-hidden border border-white/10">
                    {(selected.u||'').split('').map((c, i) => (
                      <span key={'u'+i} className="w-10 h-10 flex items-center justify-center border-r border-white/5 text-on-surface-variant text-lg bg-white/[0.03]">{c}</span>
                    ))}
                    {(selected.v||'').split('').map((c, i) => (
                      <span key={'v'+i} title="Pump v" className="w-10 h-10 flex items-center justify-center border-r border-gold/40 text-gold text-lg bg-gold/15 font-bold hover:bg-gold/25 cursor-help">{c}</span>
                    ))}
                    {(selected.x||'').split('').map((c, i) => (
                      <span key={'x'+i} className="w-10 h-10 flex items-center justify-center border-r border-violet/30 text-lavender text-lg bg-violet/10">{c}</span>
                    ))}
                    {(selected.y||'').split('').map((c, i) => (
                      <span key={'y'+i} title="Pump y" className="w-10 h-10 flex items-center justify-center border-r border-gold/40 text-gold text-lg bg-gold/15 font-bold hover:bg-gold/25 cursor-help">{c}</span>
                    ))}
                    {(selected.z||'').split('').map((c, i) => (
                      <span key={'z'+i} className="w-10 h-10 flex items-center justify-center border-r border-white/5 text-on-surface-variant text-lg bg-white/[0.03]">{c}</span>
                    ))}
                  </div>
                </div>
                
                <div className="flex gap-8 text-xs text-on-surface-variant/70 mb-8 p-3 rounded-lg bg-[#0e0e0e]/50 border border-white/5 overflow-x-auto">
                  <span className="flex flex-col"><span className="uppercase tracking-widest text-[9px] mb-1">u prefix</span><span className="text-cream">{selected.u || 'ε'}</span></span>
                  <span className="flex flex-col"><span className="uppercase tracking-widest text-[9px] mb-1 text-gold">Pumped v</span><span className="text-gold font-bold">{selected.v || 'ε'}</span></span>
                  <span className="flex flex-col"><span className="uppercase tracking-widest text-[9px] mb-1 text-lavender">x core</span><span className="text-lavender">{selected.x || 'ε'}</span></span>
                  <span className="flex flex-col"><span className="uppercase tracking-widest text-[9px] mb-1 text-gold">Pumped y</span><span className="text-gold font-bold">{selected.y || 'ε'}</span></span>
                  <span className="flex flex-col"><span className="uppercase tracking-widest text-[9px] mb-1">z suffix</span><span className="text-cream">{selected.z || 'ε'}</span></span>
                </div>

                <div className="flex items-center gap-4 mb-4">
                  <label className="font-label text-[10px] uppercase tracking-[0.3em] text-lavender/60 shrink-0">Pump i = {pumpCount}</label>
                  <input type="range" min={0} max={4} value={pumpCount} onChange={e => setPumpCount(+e.target.value)} className="flex-1 accent-gold" />
                </div>
                <div className="space-y-3">
                  {[0, 1, 2, 3, 4].map(i => {
                    const pumped = pumpedAtI(i)
                    return (
                      <div key={i} className={'flex items-center gap-4 px-4 py-3 rounded-xl transition-all duration-300 border ' +
                        (i === pumpCount ? 'bg-gold/10 border-gold/30 shadow-[0_0_20px_rgba(255,219,60,0.15)] scale-[1.02]' : 'border-white/5 bg-white/[0.02] hover:bg-white/[0.04]')}>
                        <span className={'text-[10px] uppercase tracking-widest font-label w-12 ' + (i === pumpCount ? 'text-gold' : 'text-on-surface-variant')}>i = {i}</span>
                        <div className="flex flex-wrap gap-0">
                          {pumped.split('').map((c, j) => (
                            <span key={j} className={'w-7 h-7 flex items-center justify-center text-sm border border-white/5 ' + (i === pumpCount ? 'text-cream border-white/10' : 'text-on-surface-variant/60')}>{c}</span>
                          ))}
                          {pumped.length === 0 && <span className="text-on-surface-variant/40 italic text-sm">ε</span>}
                        </div>
                        <span className={'text-xs ml-auto font-label ' + (i === pumpCount ? 'text-cream' : 'text-on-surface-variant/50')}>|s| = {pumped.length}</span>
                      </div>
                    )
                  })}
                </div>
              </div>
            </div>
          ) : (
            <div className="glass-panel rounded-3xl flex items-center justify-center fade-up" style={{ minHeight: 500, animationDelay: '0.2s' }}>
              <div className="text-center">
                <span className="material-symbols-outlined text-6xl text-white/5 block mb-4">water</span>
                <p className="text-on-surface-variant text-sm font-label uppercase tracking-widest">Ask about a language to see the CFL pumping lemma</p>
              </div>
            </div>
          )}
        </div>
      </div>
      <RAGPanel 
        simulatorId="cfl-pumping" unit="unit3" 
        onLoadAutomata={(type, payload) => {
          if (type === 'pumping_cfl' || type === 'pumping') {
            setSelected(payload)
            setQuery(payload.language)
          }
        }} 
      />
    </div>
  )
}
